import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Container, Heading, Box, Text } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import { useTheme } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const theme = useTheme();
  console.log(theme);
  return (
    <>
      <Head>
        <title>RCT-201 Evaluation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container textAlign={"center"} maxW={"lg"} mt="1rem">
        <Heading>Welcome to the C4 evaluation for </Heading>
        <Heading color="orange" m="1.5rem">
          RCT-201
        </Heading>
        <Box>
          <Text m="1.5rem" fontSize={"1.3rem"}>
            You need to create an application similar to the one that you are
            looking right now. There 2 pages that needs to be created apart from
            the current homepage.
          </Text>
        </Box>
      </Container>
    </>
  );
}
